#!/bin/bash

# ############################################################
# DO NOT MODIFY BELOW HERE UNLESS YOU KNOW WHAT YOUR ARE DOING
# ############################################################

echo "Setting up Git..."

echo -n "  Aliasing commands..."
alias gs="git s" # git status
alias gpf="git pusf"
alias gpul="git pul"
alias gpus="git pus"
alias gk="git ck" # git checkout
alias gkb="git ck -b" # git checkout -b
alias gkm="git ck master" # git checkout master
alias gkn="git ck next" # git checkout next
alias gkd="git ck dev" # git checkout dev
alias gc="git co"
alias gco="git co"
alias gbdm="git branch --merged | egrep -v \"^\*|master|next|dev|stg\" | xargs -n 1 git branch -d" # Delete local branches that have been merged and are not master or next
alias ga="git a"
alias gi="git ig"
alias gf="git f"
alias gfp="git fpr && git p"
alias gfpr="git fpr"
alias giu="git igu"
alias ggo="git go"
alias ggr="git go"
alias gb="git b"
alias gba="git ba"
alias gbd="git bd"
alias gbde="git bde"
alias gbl="git bl"
alias gmffo="git mffo" # git merge --ff--only
alias gpo="git po"
alias gpuo="git puo"
alias gra="git ra"
alias grh="git rh"
alias grv="git rv"
alias grre="git rre"
alias grrm="git rrm"
alias grv="git rv"
alias gst="git sth"
alias gsts="git sths"
alias gstp="git sthp"
alias gstl="git sthl"
alias gls="git config --global"
alias gitalias="alias | egrep \"^g\" | sort"

gls alias.a "add -A"
gls alias.b "branch"
gls alias.ba "branch -a"
gls alias.bl "branch -l"
gls alias.bd "branch -d"
gls alias.bde "branch -D"
gls alias.ck "checkout"
gls alias.co "commit -am"
gls alias.d "diff"
gls alias.dc "diff --cached"
gls alias.f "fetch"
gls alias.fpr "fetch -p"
gls alias.ig "update-index --assume-unchanged "
gls alias.igu "update-index --no-assume-unchanged "
gls alias.go "log --graph --pretty=oneline --abbrev-commit"
gls alias.gr "log --graph"
gls alias.lc "log ORIG_HEAD.. --stat --no-merges"
gls alias.lp "log --patch-with-stat"
gls alias.mnf "merge --no-ff"
gls alias.mnff "merge --no-ff"
gls alias.mffo "merge --ff-only"
gls alias.mt "mergetool"
gls alias.pul "pull"
gls alias.po "pull origin"
gls alias.pus "push"
gls alias.pusf "push -f"
gls alias.puo "push -u origin"
gls alias.ra "remote add"
gls alias.rre "remote rename"
gls alias.rrm "remote remove"
gls alias.rv "remote -v"
gls alias.rh "reset --hard"
gls alias.s "status"
gls alias.st "status"
gls alias.sttaus "status"
gls alias.sattus "status"
gls alias.stauts "status"
gls alias.staus "status"
gls alias.sttus "status"
gls alias.stm "status --untracked=no"
gls alias.stfu "status --untracked=no"
gls alias.sth "stash"
gls alias.sths "stash save"
gls alias.sthp "stash pop"
gls alias.sthl "stash list"
echo " \033[32m✔\033[0m."

echo "Git setup complete \033[32m✔\033[0m."
